### PR TITLE
feat: replace legacy action with build push action

### LINKED ISSUE #46: CI: replace matootie/github-docker with docker/build-push-action
## Description

https://github.com/matootie/github-docker has been archived and https://github.com/docker/build-push-action is actively maintained.

See: https://github.com/matootie/github-docker#disclaimer.

## Completion Criteria

CI jobs use https://github.com/docker/build-push-action

### PR DESCRIPTION
**Pull request by wep21**
Closes #46

### CODE REVIEW

**Comment by wep21** [comment]
cc @christophebedard

**Review by christophebedard — APPROVED** [review]
LGTM, thanks @wep21!

**Comment by christophebedard** [comment]
@wep21 do you know why some of the jobs are failing?

* https://github.com/ros-tooling/setup-ros-docker/actions/runs/2097331352
* https://github.com/ros-tooling/setup-ros-docker/actions/runs/2099675759

**Comment by christophebedard** [comment]
> @christophebedard Could you delete the legacy github packages such as [ros-tooling/setup-ros-docker/packages/207980](https://github.com/ros-tooling/setup-ros-docker/packages/207980)?

you mean the images with `:mrXY` tags? Like `:mr44` for that one?

**Comment by wep21** [comment]
I mean the ones start with `docker.pkg.github.com`.

**Comment by christophebedard** [comment]
> @christophebedard I mean the ones start with `docker.pkg.github.com`.

done, sorry for the delay. I wanted to make sure this wasn't going to break existing workflows. Seems like it shouldn't.

**Pull request merged**
