### PR TITLE
feat: add humble distribution

### LINKED ISSUE #49: Add support for Humble Hawksbill (May 2022)
## Description

Humble will be released in May 2022: https://docs.ros.org/en/rolling/Releases/Release-Humble-Hawksbill.html#release-timeline

`setup-ros-docker` should support it, but we might want to wait until Humble is officially released.

## Completion Criteria

Humble is supported by `setup-ros-docker`.

## Implementation Notes / Suggestions

Add to list of images.

## Testing Notes / Suggestions

N/A.

### PR DESCRIPTION
**Pull request by wep21**
Humble distribution will be released today, so I added humble distribution into `ros_distro`.
Closes #49

### CODE REVIEW

**Comment by christophebedard** [comment]
Thanks @wep21! We'll re-run CI once Humble is released in the normal repo.

**Review by christophebedard — APPROVED** [review]
Thanks @wep21!

**Comment by wep21** [comment]
@christophebedard I guess these images below are still old, so push action is failed.
https://github.com/ros-tooling/setup-ros-docker/pkgs/container/setup-ros-docker%2Fsetup-ros-docker-ubuntu-bionic
https://github.com/ros-tooling/setup-ros-docker/pkgs/container/setup-ros-docker%2Fsetup-ros-docker-ubuntu-focal
https://github.com/ros-tooling/setup-ros-docker/runs/6562679932?check_suite_focus=true
Could you remove them from pkgs once?

**Comment by christophebedard** [comment]
@wep21 done, the jobs now pass:

* https://github.com/ros-tooling/setup-ros-docker/runs/6574786096?check_suite_focus=true
* https://github.com/ros-tooling/setup-ros-docker/runs/6574786223?check_suite_focus=true

**Pull request merged**
