### PR TITLE
Update colcon-* versions

### LINKED ISSUE #41: colcon-package-selection is old
## Description

Since `colcon-package-selection` in `setup-ros-docker` is old, some options like `--packages-above-and-dependencies` are not supported.

### Expected Behavior

Users can use as many options as possible that the latest version has.

### Actual Behavior

Users can't use `--packages-above-and-dependencies`.

## To Reproduce

As I've tested on CI, please see the following results.

1. Current version (0.2.6)

`osrf/ros:galactic-desktop` passed (because it's using apt-version of colcon) but `setup-ros-docker` failed.

https://github.com/kenji-miyake/setup-ros-test-colcon-version/pull/1

2. After manually updating colcon-package-selection from 0.2.6 to 0.2.10

Both `osrf/ros:galactic-desktop` and `setup-ros-docker` passed.
https://github.com/kenji-miyake/setup-ros-test-colcon-version/pull/2

## System (please complete the following information)

 - OS: Ubuntu 20.04
 - ROS 2 Distro: Galactic

### PR DESCRIPTION
**Pull request by kenji-miyake**
Resolves #41

### CODE REVIEW

**Comment by christophebedard** [comment]
This looks good to me, but since there's no tagging/versioning for these images, it means that, if someone is using an older version of `action-ros-ci`, their CI might start failing like https://github.com/ros-tooling/action-ros-ci/issues/615. I think we could just update everything but keep `colcon-mixin` to `<0.1.10` in order to avoid failures like that and then figure out what to do about `colcon-mixin` afterwards.

**Comment by kenji-miyake** [comment]
@christophebedard I'm sorry, I forgot to change as you suggested. Now it's done.
Also, as for the versioning, do you have any plan for that?

**Comment by christophebedard** [comment]
> @christophebedard I'm sorry, I forgot to change as you suggested. Now it's done.

Thanks! Were you able to test it with `action-ros-ci` @ v0.2? It might also be a good idea to test it with v0.1 just to make sure.

> Also, as for the versioning, do you have any plan for that?

I would let @emersonknapp answer this.

**Comment by kenji-miyake** [comment]
@christophebedard 
> Were you able to test it with action-ros-ci @ v0.2?

Not yet.
How can I test with the Docker image that will be created in this PR? :thinking: 
I guess Docker images won't be published from PRs.

**Comment by christophebedard** [comment]
> How can I test with the Docker image that will be created in this PR? 
> I guess Docker images won't be published from PRs.

You can probably modify the workflow config on your fork and get it to build the image on a branch other than `master`. Then you can use the image from your fork (like `kenji-miyake/setup-ros-docker:...`).

**Comment by kenji-miyake** [comment]
@christophebedard Okay, I'll try it!

**Review by emersonknapp — CHANGES_REQUESTED** [review]
As per discussion on tracking issue - adding my review to clear it from my queue for now

**Comment by emersonknapp** [comment]
Closing as stale for now - please open new PR if change will be worked on in the future

**Pull request closed without merging**
