### PR TITLE
feat: replace legacy action with build push action

### LINKED ISSUE #46: CI: replace matootie/github-docker with docker/build-push-action
## Description

https://github.com/matootie/github-docker has been archived and https://github.com/docker/build-push-action is actively maintained.

See: https://github.com/matootie/github-docker#disclaimer.

## Completion Criteria

CI jobs use https://github.com/docker/build-push-action

### PR DESCRIPTION
**Pull request by wep21**
Closes #46

### CODE REVIEW

**Comment by wep21** [comment]
cc @christophebedard

**Comment by christophebedard** [comment]
Thanks for working on this @wep21! Could you push your branch to this repo (instead of a fork) and create another PR with that branch? Otherwise, CI cannot have access to the secrets and we can't really know if your changes work since it fails early.

**Comment by wep21** [comment]
@christophebedard Sure. Unfortunately, I don't have the write access right to this repository. Could you give me the write access right to me?

**Comment by wep21** [comment]
@christophebedard Thank you! I created #48.

**Pull request closed without merging**
